// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: protos/pokemon.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{0}
}

type Pokemon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Height int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight int32    `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Types  []string `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *Pokemon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pokemon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pokemon) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Pokemon) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Pokemon) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type PokemonTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PokemonTypeRequest) Reset() {
	*x = PokemonTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonTypeRequest) ProtoMessage() {}

func (x *PokemonTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonTypeRequest.ProtoReflect.Descriptor instead.
func (*PokemonTypeRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *PokemonTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PokemonList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon []*Pokemon `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
}

func (x *PokemonList) Reset() {
	*x = PokemonList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonList) ProtoMessage() {}

func (x *PokemonList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonList.ProtoReflect.Descriptor instead.
func (*PokemonList) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{3}
}

func (x *PokemonList) GetPokemon() []*Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type AddPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pokemon *Pokemon `protobuf:"bytes,1,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
}

func (x *AddPokemonRequest) Reset() {
	*x = AddPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPokemonRequest) ProtoMessage() {}

func (x *AddPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPokemonRequest.ProtoReflect.Descriptor instead.
func (*AddPokemonRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{4}
}

func (x *AddPokemonRequest) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type PokemonNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PokemonNameRequest) Reset() {
	*x = PokemonNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonNameRequest) ProtoMessage() {}

func (x *PokemonNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonNameRequest.ProtoReflect.Descriptor instead.
func (*PokemonNameRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{5}
}

func (x *PokemonNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePokemonRequest) Reset() {
	*x = DeletePokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePokemonRequest) ProtoMessage() {}

func (x *DeletePokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePokemonRequest.ProtoReflect.Descriptor instead.
func (*DeletePokemonRequest) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePokemonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PokemonExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *PokemonExistsResponse) Reset() {
	*x = PokemonExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pokemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonExistsResponse) ProtoMessage() {}

func (x *PokemonExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pokemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonExistsResponse.ProtoReflect.Descriptor instead.
func (*PokemonExistsResponse) Descriptor() ([]byte, []int) {
	return file_protos_pokemon_proto_rawDescGZIP(), []int{7}
}

func (x *PokemonExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_protos_pokemon_proto protoreflect.FileDescriptor

var file_protos_pokemon_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x73, 0x0a, 0x07, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x28, 0x0a,
	0x12, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x12, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x32, 0xab, 0x03, 0x0a, 0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x72, 0x69, 0x73, 0x62, 0x72, 0x61, 0x64, 0x6c, 0x65, 0x79, 0x64,
	0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x71, 0x6c, 0x69, 0x74,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_pokemon_proto_rawDescOnce sync.Once
	file_protos_pokemon_proto_rawDescData = file_protos_pokemon_proto_rawDesc
)

func file_protos_pokemon_proto_rawDescGZIP() []byte {
	file_protos_pokemon_proto_rawDescOnce.Do(func() {
		file_protos_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_pokemon_proto_rawDescData)
	})
	return file_protos_pokemon_proto_rawDescData
}

var file_protos_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_pokemon_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: pokemon.Empty
	(*Pokemon)(nil),               // 1: pokemon.Pokemon
	(*PokemonTypeRequest)(nil),    // 2: pokemon.PokemonTypeRequest
	(*PokemonList)(nil),           // 3: pokemon.PokemonList
	(*AddPokemonRequest)(nil),     // 4: pokemon.AddPokemonRequest
	(*PokemonNameRequest)(nil),    // 5: pokemon.PokemonNameRequest
	(*DeletePokemonRequest)(nil),  // 6: pokemon.DeletePokemonRequest
	(*PokemonExistsResponse)(nil), // 7: pokemon.PokemonExistsResponse
}
var file_protos_pokemon_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonList.pokemon:type_name -> pokemon.Pokemon
	1, // 1: pokemon.AddPokemonRequest.pokemon:type_name -> pokemon.Pokemon
	4, // 2: pokemon.PokemonService.AddPokemon:input_type -> pokemon.AddPokemonRequest
	5, // 3: pokemon.PokemonService.GetPokemonByName:input_type -> pokemon.PokemonNameRequest
	2, // 4: pokemon.PokemonService.GetPokemonByType:input_type -> pokemon.PokemonTypeRequest
	0, // 5: pokemon.PokemonService.GetAllPokemon:input_type -> pokemon.Empty
	6, // 6: pokemon.PokemonService.DeletePokemonById:input_type -> pokemon.DeletePokemonRequest
	5, // 7: pokemon.PokemonService.PokemonExists:input_type -> pokemon.PokemonNameRequest
	1, // 8: pokemon.PokemonService.AddPokemon:output_type -> pokemon.Pokemon
	1, // 9: pokemon.PokemonService.GetPokemonByName:output_type -> pokemon.Pokemon
	3, // 10: pokemon.PokemonService.GetPokemonByType:output_type -> pokemon.PokemonList
	3, // 11: pokemon.PokemonService.GetAllPokemon:output_type -> pokemon.PokemonList
	0, // 12: pokemon.PokemonService.DeletePokemonById:output_type -> pokemon.Empty
	7, // 13: pokemon.PokemonService.PokemonExists:output_type -> pokemon.PokemonExistsResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_pokemon_proto_init() }
func file_protos_pokemon_proto_init() {
	if File_protos_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_pokemon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Pokemon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PokemonTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PokemonList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AddPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PokemonNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pokemon_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PokemonExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_pokemon_proto_goTypes,
		DependencyIndexes: file_protos_pokemon_proto_depIdxs,
		MessageInfos:      file_protos_pokemon_proto_msgTypes,
	}.Build()
	File_protos_pokemon_proto = out.File
	file_protos_pokemon_proto_rawDesc = nil
	file_protos_pokemon_proto_goTypes = nil
	file_protos_pokemon_proto_depIdxs = nil
}
